#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/gplive/functions"

case "$1" in
  help | gplive:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
    gplive, Used to sync stats to gitpushlive.com

help_content
    }

    if [[ $1 = "gplive:help" ]] ; then
        echo -e 'Usage: dokku gplive:command '
        echo ''
        echo '  gplive:sendstats, send basic server stats to gitpushlive, auto runs every minute'
        echo '  gplive:configbackups, configures the backup settings, run from gitpushlive.com'
        echo '  gplive:addbackup [type] [name], adds a volume or service to the backup script'
        echo '  gplive:removebackup [type] [name], removes a volume or service from the backup script'
    else
        help_content_func
    fi
    ;;
  
  gplive)
    gplive_main_cmd "$@"
    ;;

  gplive:sendstats)
    gplive_sendstats_cmd "$@"
    ;;

  gplive:list)
    gplive_list_cmd "$@"
    ;;

  gplive:add)
    gplive_add_cmd "$@"
    ;;
  
  gplive:remove)
    gplive_remove_cmd "$@"
    ;;

  gplive:configbackups)
    gplive_configbackups_cmd "$@"
    ;;
  gplive:backup)
    gplive_backup_cmd "$@"
    ;;   
  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac