#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/gplive/functions"

case "$1" in
  help | gplive:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
    gplive, returns data about all apps
    gplive:sendstats, send basis server stats to gitpushlive   
    gplive:update, updates plugin
help_content
    }

    if [[ $1 = "gplive:help" ]] ; then
        echo -e 'Usage: dokku gplive'
        echo ''
        echo 'Gets all the data from an app or all apps for syncing with gplive.com'
        echo ''
        echo 'Example:'
        echo ''
        echo '$ dokku gplive'
        echo ''
    else
        help_content_func
    fi
    ;;
  
  gplive)
    gplive_main_cmd "$@"
    ;;

  gplive:update)
    gplive_autoupdate_cmd "$@"
    ;;

  gplive:sendstats)
    gplive_sendstats_cmd "$@"
    gplive_autoupdate_cmd "$@"
    ;;
  
  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac