#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$DOKKU_DISTRO" in
  ubuntu)
    if [[ -z $(which curl) ]]; then
      export DEBIAN_FRONTEND=noninteractive
      apt-get install -qq -y curl
    fi
    ;;
esac

# remove cron if it already exists
[ -f /etc/cron.d/gplive ] && rm /etc/cron.d/gplive
# create cron to run every minute to update stats
echo "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin">/etc/cron.d/gplive
echo "* * * * * root dokku gplive:sendstats>/dev/null">>/etc/cron.d/gplive