#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/gplive/functions"

APP="$1"
APP_ROOT="$DOKKU_ROOT/$APP"

gplive_updateapp_cmd $APP $APP_ROOT "stopped"