#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

gitpushlive_main_cmd() {
  declare desc="prints Hello \$APP"
  local cmd="gitpushlive"
  local app

  dokku_log_info2_quiet "My Apps"
  for app in $(dokku_apps); do
    echo "$app"
  done
}

gitpushlive_main_cmd "$@"